<?php
header('Content-Type: application/json');
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'includes/PHPMailer/src/Exception.php';
require 'includes/PHPMailer/src/PHPMailer.php';
require 'includes/PHPMailer/src/SMTP.php';

$data = json_decode(file_get_contents('php://input'), true);
$fullName = htmlspecialchars($data['fullName']);
$email = $data['email'];
$phone = htmlspecialchars($data['phone']);
$practiceArea = htmlspecialchars($data['practiceArea']);
$caseDescription = htmlspecialchars($data['caseDescription']);
$consultMode = htmlspecialchars($data['consultMode']);
$inquiryId = 'JHA-' . date('Y') . '-' . rand(1000, 9999);

$mail = new PHPMailer(true);

try {
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com'; 
    $mail->SMTPAuth = true;
    $mail->Username = 'advocateakj2017@gmail.com'; 
    $mail->Password = 'mjti mrbm iyjx itnc'; 
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->Port = 587;
    $mail->setFrom('advocateakj2017@gmail.com', 'Jha & Associates');

    // --- 1. EMAIL TO CLIENT (CONFIRMATION) ---
    $mail->addAddress($email);
    $mail->isHTML(true);
    $mail->Subject = 'Consultation Request Received - Ref: ' . $inquiryId;
    $mail->Body = '
    <div style="font-family: sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
        <div style="background: #0f172a; padding: 25px; text-align: center;">
            <h1 style="color: #c5a059; margin: 0;">JHA & ASSOCIATES</h1>
        </div>
        <div style="padding: 30px;">
            <h2 style="color: #1e293b;">Hello ' . $fullName . ',</h2>
            <p>Thank you for reaching out. We have received your inquiry.</p>
            <div style="background: #f8fafc; padding: 15px; border-radius: 8px; border-left: 5px solid #c5a059;">
                <p style="margin:0; font-weight:bold;">Reference Number: ' . $inquiryId . '</p>
            </div>
            <p>Our team is reviewing your <strong>' . $practiceArea . '</strong> matter and will contact you via <strong>' . $consultMode . '</strong> within 24 hours.</p>
        </div>
    </div>';
    $mail->send();

    // --- 2. EMAIL TO ADVOCATE (NEW INQUIRY ALERT) ---
    $mail->clearAddresses();
    $mail->addAddress('advocateakj2017@gmail.com');
    $mail->Subject = '🚨 NEW INQUIRY: ' . $inquiryId;
    $mail->Body = '
    <div style="font-family: sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 12px; overflow: hidden;">
        <div style="background: #c5a059; padding: 20px; color: white; text-align: center;">
            <h2>🚨 New Consultation Request</h2>
        </div>
        <div style="padding: 25px;">
            <table width="100%" style="border-collapse: collapse;">
                <tr><td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>👤 Name:</strong> ' . $fullName . '</td></tr>
                <tr><td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>📞 Phone:</strong> <a href="tel:' . $phone . '">' . $phone . '</a></td></tr>
                <tr><td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>📧 Email:</strong> ' . $email . '</td></tr>
                <tr><td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>⚖️ Category:</strong> ' . $practiceArea . '</td></tr>
                <tr><td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>📹 Mode:</strong> ' . $consultMode . '</td></tr>
            </table>
            <div style="margin-top: 20px; background: #fdf6e3; padding: 15px; border-radius: 8px;">
                <strong>📝 Description:</strong><br>' . nl2br($caseDescription) . '
            </div>
        </div>
        <div style="background: #f1f1f1; padding: 15px; text-align: center; font-size: 12px;">
            Generated by Jha & Associates CRM System
        </div>
    </div>';
    $mail->send();

    echo json_encode(['success' => true, 'message' => 'Emails sent successfully']);
} catch (Exception $e) {
    echo json_encode(['success' => false, 'message' => $mail->ErrorInfo]);
}
?>
